# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: terrapixel
email: bennet@becker-dd.de
description: >- # this means to ignore newlines until "baseurl:"
        This contain documentation and explaintio to my project called terrapixel.
        From a set of source images it create meta-image in a mosaic fashion.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://terrapixel.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bennet0496
github_username:  bennet0496

heading_anchors: true


color_scheme: terrapixel

logo: "assets/images/logo_head.png"
footer_content: "Copyright &copy; 2020 Bennet Becker. Distributed by an <a href=\"https://github.com/bennet0496/terrapixel/tree/master/LICENSE\">MIT license.</a>"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

aux_links:
  "terrapixel":
    - "https://terrapixel.me/"
  "imprint":
    - "https://terrapixel.me/imprint.html"
  "privacy statement":
      - "https://terrapixel.me/dataprotection.html"


# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-responsive-image

kramdown:
  parse_block_html: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
